import SwiftUI


let funFactsList = [
    01: "Fun Facts Infographics",
    02: "Bangkok is the world’s most visited city.",
    03: "Typing keyboards used to be arranged alphabetically.",
    04: "We are born with only 2 natural fears: the fear of falling and the fear of loud sounds.",
    05: "Baked beans are not actually baked.",
    06: "Antarctica is the only continent without any reptiles or snakes.",
    07: "Video games help surgeons perform better.",
    08: "Tomato ketchup was used as medicine for 16 years.",
    09: "The brain is the fattest organ.",
    10: "Australia has the most number of venomous snakes worldwide.",
    11: "Dead people get goosebumps.",
    12: "You can’t move or touch William Shakespeare’s bones.",
    13: "Digging a hole to China is possible if you start in Argentina.",
    14: "A snail can sleep for three years.",
    15: "A musician named Jim Sullivan mysteriously disappeared 6 years after recording an album called “U.F.O.“",
    16: "The name for the Pringles shape is a hyperbolic paraboloid.",
    17: "There is McDonald’s in all continents except Antarctica.",
    18: "At any point in time, 0.7% of the world’s population is drunk.",
    19: "Sonic the Hedgehog isn’t his full name.",
    20: "A crocodile cannot stick its tongue out.",
    21: "Like fingerprints, everyone's tongue print is different.",
    22: "Toilet paper in France is generally pink.",
    23: "Artificial banana flavoring is based on an extinct banana.",
    24: "Four out of the ten largest statues in the world are of Buddhas.",
    25: "Squeaky floors were the best home security in 17th century Japan.",
    26: "Half of all bank robberies in the U.S. are done on a Friday.",
    27: "Tinder made its first match in Antarctica in 2014.",
    28: "Men’s dress shirt collars used to be detachable.",
    29: "The first novel in the world ended mid-sentence.",
    30: "In 2014, a missing woman on a vacation in Iceland was found in a search party for herself.",
    31: "Sneezing while traveling at 60 mph makes you close your eyes for 50 feet.",
    32: "People don’t sneeze in their sleep.",
    33: "If you make $1 every second, it will take you 2,921 years to be richer than Bill Gates.",
    34: "February used to be the last month of the year.",
    35: "Shoe shops used X-Ray machines to measure shoe sizes.",
    36: "The Big Ben in London is leaning so much that the incline is visible to the naked eye.",
    37: "Australia has the most beaches in the world.",
    38: "The national animal of Scotland is the Unicorn.",
    39: "The directors of the film Despicable Me wrote their own language for the Minions.",
    40: "Alaska had a cat mayor.",
    41: "There is an island in the Bahamas with only pigs as residents.",
    42: "Eating polar bear liver can kill a human being.",
    43: "Insects are attracted to light because of the moon.",
    44: "Lobster used to be considered the cockroach of the ocean.",
    45: "DreamWorks studios was created by a former Disney employee.",
    46: "Australia has a bright pink lake.",
    47: "Netflix spent $0 on marketing its DVD rental business, but over 6 million people still used it.",
    48: "Spiked and studded dog-collars were an Ancient Greek invention.",
    49: "A full jumbo jet tank has enough fuel to drive a car around the world four times.",
    50: "Artist Salvador Dali would get out of paying at restaurants by drawing on the checks.",
    51: "Jellyfish almost caused mass nuclear explosions in 2013.",
    52: "A seaman once set a ship on fire to get out of work early.",
    53: "Tea bags were an accidental invention.",
    54: "Your heart beats 100,000 times a day.",
    55: "J is the only letter that doesn’t appear on the periodic table.",
    56: "A man once won a horse race after he died.",
    57: "At birth, baby pandas are smaller than mice.",
    58: "Jack Daniel was believed to die from kicking a safe.",
    59: "A coffee taster has his tongue insured for £10 million.",
    60: "Herring fish communicate by farting.",
    61: "A kimono literally translates to “thing to wear.”",
    62: "Scientists grew a human tooth from scratch using pee",
    63: "Tic Tacs got their name from the sound they make.",
    64: "You could go to jail for collecting eagle feathers in the U.S.",
    65: "78% of NFL players undergo financial crisis by 2 years of retirement.",
    66: "Moon Trees are a thing.",
    67: "A filmmaker once created a 10-hour “film” of paint drying.",
    68: "During the first 5 months of Pokémon Go, gaming-related accidents increased by 26.5%.",
    69: "If you ate nothing but rabbit meat, you would die from protein poisoning.",
    70: "Hundreds of rare animals and plants thrive in the North Korea-South Korea border.",
    71: "The tongue is the only muscle in the body attached from one end.",
    72: "In a conversation, each speaker’s “turn” is 2 seconds, with intervals between turns only 200 milliseconds.",
    73: "Sleep literally cleanses your brain.",
    74: "Sudan has the most pyramids out of any country.",
    75: "The Lego Group is the most powerful brand in the world.",
    76: "Mr. and Mrs. came from the words master and mistress.",
    77: "The only difference between kosher salt and table salt is the grain size.",
    78: "Humans specifically have eyes that face forward for the purpose of seeing in 3D.",
    79: "The founder of Pringles, Fredric Baur, requested to be buried in a Pringles can.",
    80: "The sound of a Star Wars lightsaber is the combined sound of a film projector and noise from an old TV.",
    81: "Humans can’t taste food without saliva.",
    82: "There’s a plankton that reverses your feeling of hot and cold.",
    83: "You can eat the stickers on fruit.",
    84: "Scientists don’t know what causes the shower-curtain effect.",
    85: "The Chanel double C was the first designer logo of all time.",
    86: "Giraffes have less neck bones than a sloth.",
    87: "The word “friends” is said in every episode of Friends.",
    88: "Manatees can get cold stress.",
    89: "Not sporty? Try aggressive sitting.",
    90: "27,000 trees are cut per day for the world’s toilet paper.",
    91: "May 22nd is the least common birth date.",
    92: "No one knows for sure how dinosaurs mate.",
    93: "Airport runway numbers actually indicate the direction on a compass.",
    94: "Hershey’s Kisses were named that after the kissing sound the chocolate makes on the conveyor belt.",
    95: "Butterflies taste with their feet.",
    96: "Penguins can jump as high as 9 feet in the air.",
    97: "Polar bears aren’t purely left-handed.",
    98: "A frog can throw up an entire organ.",
    99: "The legs of a bat are so thin, they can’t walk.",
    100: "The katydid bug hears through holes in its hind legs.",
    101: "Slugs only have one nose.",
    102: "A shrimp's heart is in its head.",
    103: "Chickens are eaten for their whole life cycle.",
    104: "Sharks can “blink” and “wink”.",
    105: "Toilets usually flush in E flat.",
    106: "A raisin dropped in fresh champagne will keep bouncing up and down from the bottom to the top of the glass.",
    107: "It takes 142.18 licks to reach the center of a Tootsie pop.",
    108: "Human birth control pills work on gorillas.",
    109: "When the first Star Wars movie came out, France was still executing people with the guillotine.",
    110: "Queen Elizabeth II owns the swans in England.",
    111: "During World War II, the Oscar awards were made of painted plaster.",
    112: "For every non-porn webpage, there are five porn pages.",
    113: "Napoléon Bonaparte’s penis was stolen.",
    114: "M&M’s stands for “Mars & Murrie’s.”",
    115: "Millions of trees were estimated to be planted by squirrels that forgot their buried nuts.",
    116: "A pound of houseflies contains more protein than a pound of beef.",
    117: "Cats sleep for ⅔ of their lives.",
    118: "Alfred Hitchcock's Psycho was the first American film to show a toilet being flushed on screen.",
    119: "The Eiffel Tower leans away from the sun.",
    120: "A laughing epidemic made 14 schools close in East Africa.",
    121: "The youngest parents in the world were aged 8 and 9.",
    122: "During WWI, Kotex was first manufactured as bandages.",
    123: "Drinking coffee in Turkey was once punishable by death.",
    124: "The Speaker of the House isn’t allowed to speak in England.",
    125: "Crocodile poop was the first contraceptive.",
    126: "The youngest Pope elected was 11 years old.",
    127: "Only 2 countries don’t sell Coca-Cola.",
    128: "The Paris Agreement on climate change was signed by the largest number of countries ever in one day.",
    129: "The world's quietest room is located at Microsoft's headquarters in Washington state.",
    130: "Only 3 countries don’t use the metric system.",
    131: "President Bush was re-elected by less than 31% of all eligible voters in the United States.",
    132: "Wayne's World was filmed in two weeks.",
    133: "Dodge made the first engines used by Ford.",
    134: "In Ancient Egypt, priests plucked their bodies bald.",
    135: "The population of the United States increases by one person every 12 seconds.",
    136: "Toto was paid $125 per week while filming The Wizard of Oz.",
    137: "The electric chair was invented by a dentist.",
    138: "Frankenstein is a vegetarian.",
    139: "The Terminator script was sold for a dollar.",
    140: "Computer mouse speed is measured in 'Mickeys'",
    141: "Pigeon poop is property of the British royal family",
    142: "Ancient Egyptians slept on pillows made of stone.",
    143: "The microwave oven was another accidental invention.",
    144: "In Elizabethan England, the spoon was so novel and prized that people carried their own folding spoons to banquets.",
    145: "Millie the White House dog earned more than four times as President Bush in 1991.",
    146: "Nebraskan drivers had the flashiest traffic situation back then.",
    147: "Over 70% of people would reveal their passwords for chocolate.",
    148: "A Boeing 747 airliner is made of over 6,000,000 separate parts.",
    149: "The word 'testify' is based on… testes?",
    150: "“Pants” used to be a dirty word.",
    151: "Palindromes are the most difficult kind of phrase to form.",
    152: "The oceans contain 200,000 different kinds of viruses.",
    153: "The tallest tower of cupcakes ever made is over 35 feet.",
    154: "The biggest grill out of all time had 394 people grilling meat.",
    155: "The average person will spend six months of their life waiting for red lights to turn green.",
    156: "A single lightning bolt has enough energy to toast 100,000 slices of bread.",
    157: "A blue whale's heartbeat can be heard from two miles away.",
    158: "The Netherlands has a squirrel bridge.",
    159: "Subway footlongs don’t measure a foot long.",
    160: "Marie Curie's belongings still have radioactive residue in present day.",
    161: "The Canary Islands are named after dogs, not birds.",
    162: "The Netherlands has the tallest population.",
    163: "Indonesia has the shortest population.",
    164: "Tom Hanks was not paid for Forrest Gump.",
    165: "Arnold Schwarzenegger once forgot to take off the Terminator look.",
    166: "The sound of the automatic doors opening on the U.S.S. Enterprise is made by a toilet.",
    167: "Will Smith wanted to adopt the German Shepherd in I Am Legend.",
    168: "Henry Cavill’s muscles are the real deal.",
    169: "The Titanic film runs for as long as the ship sunk.",
    170: "Sylvester Stallone landed in the I.C.U. while filming Rocky.",
    171: "Brad Pitt and Edward Norton actually learned how to make soap in Fight Club.",
    172: "Brendan Fraser almost died filming The Mummy.",
    173: "Arnold Schwarzenegger practiced with guns every day for a month to prepare for The Terminator.",
    174: "Daniel Kaluuya was given the lead role on the spot after nailing his audition.",
    175: "Michael Fassbender had makeup artists put alcohol on his mustache for a role.",
    176: "The Kingsman underwater scene was not scripted.",
    177: "The creators of Stranger Things wanted to direct the It remake.",
    178: "There were 25 snakes found on The Maze Runner set.",
    179: "Crushed vitamins have been used for cocaine scenes in movies.",
    180: "Nestlé supplied 1,850 bars of real chocolate for Charlie and the Chocolate Factory.",
    181: "Hugh Jackman went 36 hours without water for Les Miserables.",
    182: "Jim Caviezel was struck by lightning while playing Jesus in The Passion Of The Christ.",
    183: "Victorians said 'prunes' when taking pictures.",
    184: "The foil seals on medicine bottles were placed due to poisoning incidents.",
    185: "North Koreans are shorter than South Koreans.",
    186: "Indians read the most out of any nationality.",
    187: "A pig was once held in trial for the death of a child.",
    188: "You could buy a town from eBay.",
    189: "Doritos are flammable.",
    190: "Starbucks flopped in Australia.",
    191: "Glaciers make sounds.",
    192: "The first roller coaster was invented to stop sinful behavior.",
    193: "Your nails grow at the same time as continental plates drift.",
    194: "The longest location name on the planet is 85 letters long.",
    195: "The people who are currently alive are only 7% of the total number of people who have ever lived.",
    196: "Muhammad is the most popular name in the world.",
    197: "There are more than 24 time zones around the world.",
    198: "Sweden has the most islands of any country.",
    199: "The red-billed quelea is the most common bird on Earth.",
    200: "The hashtag symbol is called an octothorpe.",
    201: "The longest wedding veil was longer than 63 football fields.",
    202: "No real astronaut ever said, 'Houston, we have a problem'",
    203: "The lyrebird can make chainsaw sounds.",
    204: "9% of Americans have phobias.",
    205: "Elvis only won 3 Grammys.",
    206: "Cornell University offers a wine course.",
    207: "The Krusty Krab restaurant is a lobster trap.",
    208: "The Hulk was supposed to be grey.",
    209: "The Flintstones was the highest-earning network cartoon franchise for 30 years.",
    210: "Walt Disney hated Goofy.",
    211: "The place that cartoon characters store things, just to pull out of thin air, is known as “Hammerspace”.",
    212: "Superman used to leap places instead of flying.",
    213: "The longest-running primetime animated series is the Simpsons, which began in 1987.",
    214: "Mickey Mouse and Minnie Mouse were married in real life.",
    215: "The Pokemon Hitmonlee and Hitmonchan are based on Bruce Lee and Jackie Chan.",
    216: "All the Professors in Pokemon have been named after trees.",
    217: "Snow White and the Seven Dwarfs was the first American film to have a soundtrack.",
    218: "The Little Mermaid was Disney’s first princess movie in 30 years.",
    219: "Jackie Chan voiced the Beast in the Chinese dub of The Beauty And The Beast.",
    220: "The Lion King was the first original Disney movie.",
    221: "Bees bite.",
    222: "Kids ask about 300 questions a day.",
    223: "T-shirts were originally made for unmarried men who didn't know how to sew buttons on collared shirts.",
    224: "All Froot Loops have the same flavor.",
    225: "Before the 1800s, people slept in batches.",
    226: "Cows have 'best friends' and will get stressed when separated.",
    227: "New Zealanders have more pets per household than any other country.",
    228: "The design for the seatbelts we use now was given away by Volvo.",
    229: "Kea parrots laugh together when they're in a good mood.",
    230: "Flyting was the original rap battle.",
    231: "The Russians showed up 12 days late to the 1908 Olympics.",
    232: "In Japan, letting a sumo wrestler make your baby cry is considered good luck.",
    233: "Black cats are good luck in Britain and Japan.",
    234: "Ben & Jerry learned how to make ice cream from a $5 course at Penn State.",
    235: "The the official plural form of a Prius is Prii.",
    236: "Dogs can understand up to 250 words and gestures.",
    237: "Goats have rectangular pupils.",
    238: "Wasting food is illegal for supermarkets in France.",
    239: "A baby can cost new parents 750 hours of sleep.",
    240: "A grumble is a group of pugs.",
    241: "Garfield used to own G-Mail.",
    242: "Crayola is literally 'oily chalk'.",
    243: "Abraham Lincoln was a wrestling champion.",
    244: "Queen Elizabeth II has had over 30 corgis in her lifetime.",
    245: "Relative to their bodies, Chihuahuas have the biggest brain in the dog world.",
    246: "Elvis Presley's manager sold hate merch for profit.",
    247: "Avocados never ripen on the tree.",
    248: "At the Humane Society of Missouri, kid volunteers comfort anxious shelter dogs by reading to them.",
    249: "China owns all of the pandas in the world.",
    250: "Penguins used to be 6 feet tall.",
    251: "A scientific calculator is 6 times more powerful than the Apollo 11 computer.",
    252: "Humans shed 18 kg of skin in their lifetime.",
    253: "The 'Like' button on Facebook was supposed to be the 'Awesome' button.",
    254: "Human fingers are really sensitive.",
    255: "Humans are genetically related to bananas.",
    256: "Our sense of smell and taste decrease by 20%-50% during flights.",
    257: "There are more atoms in a glass of water than glasses of water you could fill with all the oceans of the Earth.",
    258: "Bubble wrap was originally designed to be used as wallpaper.",
    259: "Your body replaces all its particles every seven years.",
    260: "The world's longest musical piece lasts 639 years.",
    261: "Neptune was the first planet that was discovered before being seen through a telescope.",
    262: "You're more likely to become President than you are to win the lottery.",
    263: "There’s only one letter that doesn’t appear in any U.S. state name.",
    264: "Samsung tests phone durability with a butt robot.",
    265: "Armadillos have bulletproof shells.",
    266: "Kleenex tissues were supposed to be for gas masks.",
    267: "Blue whales eat 500,000 calories in 1 mouthful.",
    268: "The tiny pocket in jeans is for pocket watches.",
    269: "NASA can “fax” tools to astronauts",
    270: "Only ¼ of the Sahara Desert is sandy.",
    271: "2 parts of the human body never stop growing.",
    272: "No number contains the letter A before 1,000.",
    273: "Mercedes invented a joystick-controlled car.",
    274: "The CIA headquarters Starbucks doesn’t put names on the cups.",
    275: "The Eiffel Tower grows during the summer.",
    276: "Bees can fly higher than Mount Everest.",
    277: "Humans have jumped further than horses in the Olympics.",
    278: "A waffle iron inspired one of the first iconic Nike shoes.",
    279: "Glitter was invented by a farmer.",
    280: "Abraham Lincoln used to be a bartender.",
    281: "Beethoven never studied multiplication or division.",
    282: "Aquariums were supposed to be for cows.",
    283: "An espresso maker has been sent to space.",
    284: "Apple Inc. was founded on April Fool’s.",
    285: "Wild boars wash their food.",
    286: "Baseball umpires used to sit in rocking chairs.",
    287: "The first commercial airplane flight lasted 23 minutes.",
    288: "The French Scrabble World Champion doesn’t speak French",
    289: "A U.K. woman has called 911 because of ice cream.",
    290: "The British Empire was the largest empire in the world.",
    291: "Turtles can talk to each other.",
    292: "170 year-old champagne was found under the Baltic Sea.",
    293: "Nikola Tesla did not like pearls.",
    294: "Brad Pitt injured his Achilles heel while playing Achilles.",
    295: "Martin Luther King Jr. had a C in public speaking.",
    296: "Bees can make different colors of honey.",
    297: "The Pope can’t donate organs.",
    298: "A one-armed player scored the winning goal in the first World Cup.",
    299: "The stick is the world’s first toy.",
    300: "The first baby stroller was pulled by animals.",
    301: "Ancient Egyptians used dead mice for toothaches.",
    302: "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    303: "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    304: "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
    305: "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of the iron on hot days.",
    306: "The inventor of the frisbee was turned into a frisbee after he died.",
    307: "Sea otters hold hands when they sleep to keep from drifting apart.",
    308: "Bananas are berries, but strawberries aren't.",
    309: "A single strand of spaghetti is called a 'spaghetto.'",
    310: "There are more stars in the universe than grains of sand on all the beaches on Earth.",
    311: "A day on Venus is longer than a year on Venus.",
    312: "The heart of a blue whale is about the size of a small car.",
    313: "A snail can sleep for three years.",
    314: "Octopuses have three hearts.",
    315: "The shortest commercial flight in the world is just 57 seconds long. It goes between the Scottish islands of Westray and Papa Westray.",
    316: "'E' is the most common letter in the English alphabet, appearing in 11% of all English words.",
    317: "The unicorn is the national animal of Scotland.",
    318: "An octopus has nine brains – one central brain and one in each of its eight arms.",
    319: "The Empire State Building has its own zip code.",
    320: "A jiffy is an actual unit of time. It's 1/100th of a second.",
    321: "There are more ways to shuffle a deck of cards than there are atoms on Earth.",
    322: "A group of flamingos is called a 'flamboyance.'",
    323: "The inventor of the Pringles can is now buried in one.",
    324: "Tigers have striped skin, not just striped fur.",
    325: "Cows have best friends and get stressed when they are separated.",
    326: "The speed of a computer mouse is measured in 'Mickeys.'",
    327: "A duel between three people is called a 'truel.'",
    328: "A crocodile cannot stick its tongue out.",
    329: "A group of porcupines is called a 'prickle.'",
    330: "The longest English word is 189,819 letters long. It's the chemical name for titin, the largest known protein.",
    331: "In Switzerland, it's illegal to own just one guinea pig because they get lonely.",
    332: "There's a species of jellyfish that is immortal. It can revert back to its juvenile form after becoming an adult.",
    333: "A group of owls is called a 'parliament.'",
    334: "A bolt of lightning can reach temperatures hotter than the surface of the sun.",
    335: "The oldest 'your mom' joke was discovered on a 3,500-year-old Babylonian tablet.",
    336: "The majority of your brain is fat.",
    337: "The loudest sound ever recorded was the eruption of the Krakatoa volcano in 1883, which could be heard 3,000 miles away.",
    338: "A group of frogs is called an 'army.'",
    339: "Sloths can hold their breath longer than dolphins can.",
    340: "The inventor of the telephone, Alexander Graham Bell, never called his wife or mother because they were both deaf.",
    341: "An ostrich's eye is bigger than its brain.",
    342: "The national animal of Canada is the beaver.",
    343: "The hashtag symbol is technically called an 'octothorpe.'",
    344: "A baby spider is called a 'spiderling.'",
    345: "There are 293 ways to make change for a dollar.",
    346: "The longest time between two twins being born is 87 days.",
    347: "A group of crows is called a 'murder.'",
    348: "The inventor of the Rubik's Cube didn't solve it for a month after creating it.",
    349: "A dime has 118 ridges around the edge.",
    350: "Honeybees can recognize human faces.",
    351: "The human nose can remember 50,000 different scents.",
    352: "Koalas have fingerprints almost identical to humans.",
    353: "The shortest place name is 'Å,' a village in Norway.",
    354: "A group of kittens is called a 'kindle.'",
    355: "There are more public libraries in the U.S. than McDonald's restaurants.",
    356: "The longest English word without a vowel is 'rhythms.'",
    357: "'I am.' is the shortest complete sentence in the English language.",
    358: "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    359: "The human heart beats more than three billion times in an average lifespan.",
    360: "A group of rhinos is called a 'crash.'",
    361: "The first oranges weren't orange. They were green.",
    362: "The average person will spend six months of their life waiting for red lights to turn green.",
    363: "The Guinness World Record for the most T-shirts worn at once is 260.",
    364: "The first computer virus was created in 1983.",
    365: "The longest word you can type using just the left hand is 'stewardesses.'",
    366: "The world's largest snowflake on record was 15 inches wide.",
    367: "An eagle can kill a young deer and fly away with it.",
    368: "Polar bear skin is actually black.",
    369: "A group of jellyfish is called a 'smack.'",
    370: "A single teaspoon of honey represents the life work of 12 bees.",
    371: "The inventor of the sewing machine had a dream about a needle before creating it.",
    372: "The national animal of Bhutan is the takin.",
    373: "Butterflies taste with their feet.",
    374: "The longest hiccuping spree lasted 68 years.",
    375: "The shortest war in history lasted 38 minutes (Anglo-Zanzibar War).",
    376: "The Guinness World Record for the longest time spent in zero gravity was set in 2020 by astronaut Christina Koch.",
    377: "There are more synapses (neural connections) in your brain than stars in the Milky Way galaxy.",
    378: "The largest recorded snowflake was 15 inches wide and 8 inches thick.",
    379: "Pigeons can distinguish between the works of different artists.",
    380: "A group of ravens is called an 'unkindness.'",
    381: "The English word with the most definitions is 'set.'",
    382: "The most common name in the world is 'Muhammad.'",
    383: "The oldest unopened bottle of wine was found in a Roman tomb and is over 1,650 years old.",
    384: "The largest desert in the world is Antarctica.",
    385: "A group of parrots is called a 'pandemonium.'",
    386: "The first email was sent by Ray Tomlinson to himself in 1971.",
    387: "The Great Wall of China is not visible from space without aid.",
    388: "The oldest person on record lived to be 122 years and 164 days old.",
    389: "The Mona Lisa has no eyebrows. It was the fashion in Renaissance Florence to shave them off.",
    390: "The inventor of the chocolate chip cookie sold the recipe to Nestle Toll House in exchange for a lifetime supply of chocolate.",
    391: "The Eiffel Tower can be 15 cm taller during hot days.",
    392: "Honey never spoils. Jars of honey have been found in ancient Egyptian tombs still edible after thousands of years.",
    393: "The Japanese word 'Kuchi zamishi' is the act of eating when you're not hungry because your mouth is lonely.",
    394: "A flock of sheep is called a 'trip.'",
    395: "'Stewardesses' is the longest word typed with only the left hand.",
    396: "The name 'Wendy' was made up for the book 'Peter Pan.'",
    397: "In Switzerland, it is illegal to own just one guinea pig because they get lonely.",
    398: "The shortest war in history lasted 38 minutes.",
    399: "A crocodile cannot stick its tongue out.",
    400: "A shrimp's heart is in its head.",
    401: "The moon has moonquakes.",

    ]


